workflows:
  ios-workflow:
    name: iOS Simple Workflow
    environment:
      flutter: stable
      xcode: latest
    remote_access: false
    cache:
      enabled: false  # Önbelleği geçici olarak devre dışı bırakın
    scripts:
      - name: Flutter setup
        script: |
          flutter packages pub get
      - name: iOS build
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/*.app
    publishing:
      email:
        recipients:
          - your.email@example.com